name: feldtheorie
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip>=23.3
  - numpy>=1.26
  - scipy>=1.11
  - pandas>=2.1
  - statsmodels>=0.14
  - matplotlib>=3.8
  - pyyaml>=6.0
  - pip:
      - -e .[dev]
